# Q8 - Explain what the code down below does

In [1]:
import numpy as np
from sklearn.decomposition import PCA

# Generate a synthetic dataset: 1,000 samples with 3 features each
X = np.random.rand(1000, 3)
print("Original 3D data (first 5 rows):")
print(X[0:5])

# Initialize PCA to drop 1 dimension and retain the top 2 principal components
pca = PCA(n_components=2)

# Find principal components and transform the 3D data into 2D
X2D = pca.fit_transform(X)
print("\nTransformed 2D data (first 5 rows):")
print(X2D[0:5])

# Reconstruct 3D points by projecting 2D data back into 3D space
X3D_inv = pca.inverse_transform(X2D)

# Evaluate information loss: returns False because 1 dimension of variance was discarded
is_exact_reconstruction = np.allclose(X3D_inv, X)
print("\nDoes reconstructed data match original data exactly?:")
print(is_exact_reconstruction)

Original 3D data (first 5 rows):
[[0.29685747 0.2140394  0.71911803]
 [0.23779524 0.95338277 0.74113636]
 [0.65991815 0.97519272 0.46844146]
 [0.48748375 0.00579088 0.79109025]
 [0.91400293 0.29608498 0.92994547]]

Transformed 2D data (first 5 rows):
[[ 0.35579089 -0.05469878]
 [ 0.09464083  0.54793461]
 [-0.26393629  0.25518287]
 [ 0.45253661 -0.32167396]
 [ 0.34682954 -0.34778402]]

Does reconstructed data match original data exactly?:
False


### What does the code do? 
*Answer:*

The code is demonstrating PCA using NumPy and scikit-learn to reduce a dataset 
from three dimensions down to two dimensions. It then also investigates
which information is lost when the data is being projected back.

Firstly, it generates a matrix with 1000 observations and 3 variables with
a randomly and equally divide between zero and one. The first five rows
are printed to show the dat's original 3D structuer.

Secondly, it creates a PCA-object using "n_components=2". The "fit_transform(X)" method
calculates the two most important perpendicular axis that catch the most variance in the
data. These 3D points are then projected onto a 2D space which results in 
the dataset magically becoming a 2D dataset.

Thirdly, the method "pca.inverse_transform(X2D) projects the 2D coordinates
back to the original 3D space.

And lastly, "np.allclose(X3D_inv, X) checks if the remaning data is identical
to the original data within a certain margin.

The results shows that no, it isn't identical, since the data was completely
random in the 3D space and the third aspect of each point was lost during
the dimensional reduction stage.

rip to the lost aspect :c